/** @type {import('tailwindcss').Config} */
module.exports = {
  safelist: [
    'border-border',
    'bg-primary-200',
    'text-primary-200',
    'bg-primary-300',
    'text-primary-300',
    'bg-primary-400',
    'text-primary-400',
    'bg-dark-200',
    'text-dark-200',
    'bg-dark-300',
    'text-dark-300',
    'bg-light-100',
    'text-light-100',
    'bg-light-400',
    'text-light-400',
    'bg-light-600',
    'text-light-600',
    'bg-light-800',
    'text-light-800',
    'bg-success-100',
    'text-success-100',
    'bg-success-200',
    'text-success-200',
    'bg-destructive-100',
    'text-destructive-100',
    'bg-destructive-200',
    'text-destructive-200',
    'bg-teal-50',
    'bg-teal-100',
    'bg-teal-200',
    'bg-teal-300',
    'bg-teal-400',
    'bg-teal-500',
    'bg-teal-600',
    'text-teal-50',
    'text-teal-100',
    'text-teal-200',
    'text-teal-300',
    'text-teal-400',
    'text-teal-500',
    'text-teal-600',
    'border-teal-200',
    'border-teal-300',
    'border-teal-400',
    'border-teal-500',
    'card-yellow',
    'card-blue',
    'card-green',
    'card-peach',
    'avatar-circle',
    'btn-primary',
    'btn-secondary',
    'btn-outline',
    'btn-call',
    'btn-disconnect',
    'btn-upload',
    'card-border',
    'card',
    'card-shadow',
    'card-hover',
    'form',
    'label',
    'input',
    'btn',
    'light-gradient',
    'border-gradient',
    'teal-gradient',
    'teal-gradient-subtle',
    'glass-effect',
    'pattern',
    'flex-center',
    'animate-fadeIn',
    'animate-float',
    'animate-pulse-slow',
    'animate-popup',
    'animate-message',
    'text-gradient',
  ],
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        "user-primary": "var(--user-primary)",
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--color-destructive)",
          foreground: "var(--color-destructive-foreground)",
          100: "var(--color-destructive-100)",
          200: "var(--color-destructive-200)",
        },
        success: {
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--color-popover)",
          foreground: "var(--color-popover-foreground)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        light: {
          100: "var(--color-light-100)",
          400: "var(--color-light-400)",
          600: "var(--color-light-600)",
          800: "var(--color-light-800)",
        },
        dark: {
          100: "var(--color-dark-100)",
          200: "var(--color-dark-200)",
          300: "var(--color-dark-300)",
        },
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xl: "var(--radius-xl)",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        fadeIn: {
          from: { opacity: 0, transform: "translateY(5px)" },
          to: { opacity: 1, transform: "translateY(0)" },
        },
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
          "100%": { transform: "translateY(0px)" },
        },
        popup: {
          "0%": { opacity: 0, transform: "scale(0.8) translateY(10px)" },
          "100%": { opacity: 1, transform: "scale(1) translateY(0)" },
        },
        message: {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.5 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fadeIn": "fadeIn 0.3s ease-in-out",
        "float": "float 3s ease-in-out infinite",
        "popup": "popup 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        "message": "message 0.3s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
